"""Add churn_definition to column_mappings

Revision ID: 771d5aa4985d
Revises: fb14039812c5
Create Date: 2026-02-17 18:45:56.382933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771d5aa4985d'
down_revision = 'fb14039812c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('column_mappings',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('mapping', sa.JSON(), nullable=False),
    sa.Column('churn_definition', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('column_mappings')
    # ### end Alembic commands ###
